### ISSUE TITLE
Create .gitignore file for angular

### ISSUE THREAD

**Issue by frangarcj** [ualdra/tastydra22#14]
With recommended options for an angular project

Put in /

**Comment by jri838** [comment]
@frangarcj when creating an angular project, a .gitignore file is already created.  Even so, do I continue with the issue?

**Comment by jri838** [comment]
As when creating a project in Angular its own .gitignore file is already generated, a more general gitignore will be created for the root folder, which will discard the folders generated by the different IDEs, or by the system itself.
