### ISSUE TITLE
Add GitHub notifications to a discord channel

### ISSUE THREAD

**Issue by frangarcj** [ualdra/tastydra22#4]
Create a `github`channel y `discord`and connect them both.

Follow this tutorial https://dev.to/inezabonte/how-to-get-github-notifications-on-your-discord-server-2j9o

**Comment by pcoloc** [comment]
Testing bot, **Tasty rules**

**Comment by pcoloc** [comment]
It works! 

![Captura de pantalla de 2022-03-11 19-23-58](https://user-images.githubusercontent.com/38069658/157928258-12533732-0422-4a16-8a9f-26e15aec0c12.png)

**Comment by jri838** [comment]
@paco yes, it works

**Comment by jri838** [comment]
@pcoloc Im going to put in done. It's rewieved. Good job.
