### ISSUE TITLE
Add routing and structure of pages

### ISSUE THREAD

**Issue by RozanskiP** [ualdra/tastydra22#76]

**Comment by age296** [comment]
Srry, i added 3 routes to see the components working... 
![image](https://user-images.githubusercontent.com/73339908/164889385-9fa5d4c6-4089-45a4-b8d6-b3b4549a4005.png)
Anyway, we neeed to create more routes and create lazy load after login.

**Comment by RozanskiP** [comment]
Ok, so I will add more routes in this Isues.

**Comment by RozanskiP** [comment]
I looked at the code and now it makes no sense to create more paths or links between files so I think I close issue.
